const {
  LuMail,
  LuBell,
  LuBookmark,
  LuClock,
  LuCreditCard,
  LuWallet,
  LuBanknote,
  LuCoins,
  LuShield,
  LuUser,
} = require("react-icons/lu");

export const countriesData = [
  { value: "us", label: "United States" },
  { value: "ca", label: "Canada" },
  { value: "uk", label: "United Kingdom" },
  { value: "au", label: "Australia" },
  { value: "de", label: "Germany" },
  { value: "fr", label: "France" },
  { value: "jp", label: "Japan" },
];

export const jobData = [
  { value: "dev", label: "Software Developer", category: "Technology" },
  { value: "designer", label: "UI/UX Designer", category: "Design" },
  { value: "pm", label: "Product Manager", category: "Management" },
  {
    value: "marketing",
    label: "Marketing Specialist",
    category: "Marketing",
  },
  { value: "sales", label: "Sales Representative", category: "Sales" },
  { value: "hr", label: "HR Manager", category: "Human Resources" },
  { value: "finance", label: "Financial Analyst", category: "Finance" },
  { value: "data", label: "Data Scientist", category: "Technology" },
  { value: "devops", label: "DevOps Engineer", category: "Technology" },
  { value: "qa", label: "QA Engineer", category: "Technology" },
  { value: "frontend", label: "Frontend Developer", category: "Technology" },
  { value: "backend", label: "Backend Developer", category: "Technology" },
  {
    value: "fullstack",
    label: "Full Stack Developer",
    category: "Technology",
  },
  { value: "mobile", label: "Mobile Developer", category: "Technology" },
  { value: "graphic", label: "Graphic Designer", category: "Design" },
  { value: "content", label: "Content Writer", category: "Marketing" },
  { value: "seo", label: "SEO Specialist", category: "Marketing" },
  { value: "social", label: "Social Media Manager", category: "Marketing" },
  { value: "account", label: "Account Manager", category: "Sales" },
  {
    value: "support",
    label: "Customer Support",
    category: "Customer Service",
  },
  {
    value: "admin",
    label: "Administrative Assistant",
    category: "Administration",
  },
  { value: "legal", label: "Legal Counsel", category: "Legal" },
  { value: "research", label: "Research Scientist", category: "Research" },
  { value: "teacher", label: "Teacher/Instructor", category: "Education" },
  { value: "nurse", label: "Nurse", category: "Healthcare" },
  { value: "doctor", label: "Doctor", category: "Healthcare" },
  { value: "accountant", label: "Accountant", category: "Finance" },
  { value: "analyst", label: "Business Analyst", category: "Business" },
  { value: "consultant", label: "Consultant", category: "Consulting" },
  { value: "project", label: "Project Manager", category: "Management" },
];

export const roleData = [
  {
    value: "admin",
    label: "Administrator",
    description: "Full system access",
    icon: <LuShield className="h-4 w-4" />,
  },
  {
    value: "user",
    label: "Regular User",
    description: "Limited access",
    icon: <LuUser className="h-4 w-4" />,
  },
];

export const skillData = [
  { value: "js", label: "JavaScript" },
  { value: "ts", label: "TypeScript" },
  { value: "react", label: "React" },
  { value: "vue", label: "Vue.js" },
  { value: "angular", label: "Angular" },
  { value: "node", label: "Node.js" },
  { value: "python", label: "Python" },
  { value: "java", label: "Java" },
  { value: "csharp", label: "C#" },
  { value: "php", label: "PHP" },
  { value: "ruby", label: "Ruby" },
  { value: "go", label: "Go" },
  { value: "rust", label: "Rust" },
  { value: "swift", label: "Swift" },
  { value: "kotlin", label: "Kotlin" },
  { value: "sql", label: "SQL" },
  { value: "mongodb", label: "MongoDB" },
  { value: "postgres", label: "PostgreSQL" },
  { value: "mysql", label: "MySQL" },
  { value: "redis", label: "Redis" },
  { value: "aws", label: "AWS" },
  { value: "azure", label: "Azure" },
  { value: "gcp", label: "Google Cloud" },
  { value: "docker", label: "Docker" },
  { value: "kubernetes", label: "Kubernetes" },
  { value: "git", label: "Git" },
  { value: "figma", label: "Figma" },
  { value: "sketch", label: "Sketch" },
  { value: "photoshop", label: "Photoshop" },
  { value: "illustrator", label: "Illustrator" },
];

export const notificationOptionData = [
  {
    value: "email",
    label: "Email Notifications",
    icon: <LuMail className="h-4 w-4 mr-2" />,
  },
  {
    value: "push",
    label: "Push Notifications",
    icon: <LuBell className="h-4 w-4 mr-2" />,
  },
  {
    value: "sms",
    label: "SMS Notifications",
    icon: <LuBookmark className="h-4 w-4 mr-2" />,
  },
  {
    value: "weekly",
    label: "Weekly Digest",
    icon: <LuClock className="h-4 w-4 mr-2" />,
  },
];

export const paymentOptionData = [
  {
    value: "credit",
    label: "Credit Card",
    description: "Visa, Mastercard, Amex",
    icon: <LuCreditCard className="h-4 w-4" />,
  },
  {
    value: "paypal",
    label: "PayPal",
    description: "Online payment system",
    icon: <LuWallet className="h-4 w-4" />,
  },
  {
    value: "bank",
    label: "Bank Transfer",
    description: "Direct bank transfer",
    icon: <LuBanknote className="h-4 w-4" />,
  },
  {
    value: "crypto",
    label: "Cryptocurrency",
    description: "Bitcoin, Ethereum, etc.",
    icon: <LuCoins className="h-4 w-4" />,
  },
];

export const mockBlogs = [
  {
    id: 1,
    title: "Amazing Wildlife in Africa",
    content:
      "Discover the incredible wildlife and natural beauty of African safaris and explore the diverse ecosystems. From majestic elephants to graceful giraffes, experience the wonder of nature in its purest form.",
    thumbnail: "/placeholder.svg?height=60&width=80",
    videoUrl: "https://example.com/video1.mp4",
    continent: "Africa",
    country: "Kenya",
    createdAt: "2024-01-15",
    updatedAt: "2024-01-20",
  },
  {
    id: 2,
    title: "European Architecture Tour",
    content:
      "Explore the stunning architectural marvels across European cities and discover centuries of history. From Gothic cathedrals to modern masterpieces, witness the evolution of design and craftsmanship.",
    thumbnail: "/placeholder.svg?height=60&width=80",
    videoUrl: "https://example.com/video2.mp4",
    continent: "Europe",
    country: "France",
    createdAt: "2024-01-10",
    updatedAt: "2024-01-18",
  },
  {
    id: 3,
    title: "Asian Street Food Adventure",
    content:
      "A culinary journey through the vibrant street food scenes of Asia, tasting authentic flavors. Experience the rich culture and traditions through local cuisine and cooking techniques.",
    thumbnail: "/placeholder.svg?height=60&width=80",
    videoUrl: "",
    continent: "Asia",
    country: "Thailand",
    createdAt: "2024-01-12",
    updatedAt: "2024-01-22",
  },
  {
    id: 4,
    title: "South American Landscapes",
    content:
      "Breathtaking landscapes and natural wonders of South America, from mountains to rainforests. Discover the biodiversity and natural beauty of this incredible continent.",
    thumbnail: "/placeholder.svg?height=60&width=80",
    videoUrl: "https://example.com/video4.mp4",
    continent: "South America",
    country: "Brazil",
    createdAt: "2024-01-08",
    updatedAt: "2024-01-16",
  },
  {
    id: 5,
    title: "North American National Parks",
    content:
      "Exploring the diverse ecosystems of North American national parks and their conservation efforts. From towering mountains to pristine lakes, experience nature's grandeur.",
    thumbnail: "/placeholder.svg?height=60&width=80",
    videoUrl: "https://example.com/video5.mp4",
    continent: "North America",
    country: "United States",
    createdAt: "2024-01-14",
    updatedAt: "2024-01-21",
  },
  {
    id: 6,
    title: "Asian Street Food Adventure",
    content:
      "A culinary journey through the vibrant street food scenes of Asia, tasting authentic flavors. Experience the rich culture and traditions through local cuisine and cooking techniques.",
    thumbnail: "/placeholder.svg?height=60&width=80",
    videoUrl: "",
    continent: "Asia",
    country: "Thailand",
    createdAt: "2024-01-12",
    updatedAt: "2024-01-22",
  },
  {
    id: 7,
    title: "South American Landscapes",
    content:
      "Breathtaking landscapes and natural wonders of South America, from mountains to rainforests. Discover the biodiversity and natural beauty of this incredible continent.",
    thumbnail: "/placeholder.svg?height=60&width=80",
    videoUrl: "https://example.com/video4.mp4",
    continent: "South America",
    country: "Brazil",
    createdAt: "2024-01-08",
    updatedAt: "2024-01-16",
  },
  {
    id: 8,
    title: "Asian Street Food Adventure",
    content:
      "A culinary journey through the vibrant street food scenes of Asia, tasting authentic flavors. Experience the rich culture and traditions through local cuisine and cooking techniques.",
    thumbnail: "/placeholder.svg?height=60&width=80",
    videoUrl: "",
    continent: "Asia",
    country: "Thailand",
    createdAt: "2024-01-12",
    updatedAt: "2024-01-22",
  },
];

export const continents = [
  { value: "Africa", label: "Africa" },
  { value: "Asia", label: "Asia" },
  { value: "Europe", label: "Europe" },
  { value: "North America", label: "North America" },
  { value: "South America", label: "South America" },
  { value: "Australia", label: "Australia" },
  { value: "Antarctica", label: "Antarctica" },
];

export const mockUsers = [
  {
    name: "Alice Johnson",
    email: "alice@example.com",
    phoneNumber: "1234567890",
    password: "securePass123",
    profileImage: "/images/users/alice.jpg",
    address: {
      streetAddress: "123 Main St",
      areaOrVillage: "Greenwood",
      district: "North District",
    },
    age: 29,
    gender: "Female",
    designation: "Marketing Manager",
    isEmailVerified: true,
    role: "user",
    status: "active",
  },
  {
    name: "Bob Smith",
    email: "bob@example.com",
    phoneNumber: "9876543210",
    password: "bobSecure456",
    profileImage: "/images/users/bob.jpg",
    address: {
      streetAddress: "456 Side Ave",
      areaOrVillage: "Hilltop",
      district: "East District",
    },
    age: 35,
    gender: "Male",
    designation: "Software Engineer",
    isEmailVerified: false,
    role: "special-user",
    status: "inactive",
  },
  {
    name: "Carol Lee",
    email: "carol@example.com",
    phoneNumber: "5551234567",
    password: "passCarol789",
    profileImage: "/images/users/carol.jpg",
    address: {
      streetAddress: "789 Sunset Blvd",
      areaOrVillage: "Lakeside",
      district: "West District",
    },
    age: 42,
    gender: "Female",
    designation: "Content Manager",
    isEmailVerified: true,
    role: "user",
    status: "active",
  },
  {
    name: "Daniel Rose",
    email: "daniel@example.com",
    phoneNumber: "3216549870",
    password: "daniel123",
    profileImage: "/images/users/daniel.jpg",
    address: {
      streetAddress: "22 Rose St",
      areaOrVillage: "Bloomtown",
      district: "South District",
    },
    age: 38,
    gender: "Male",
    designation: "Finance Analyst",
    isEmailVerified: true,
    role: "special-user",
    status: "inactive",
  },
  {
    name: "Eva Green",
    email: "eva@example.com",
    phoneNumber: "1122334455",
    password: "evaSecure",
    profileImage: "/images/users/eva.jpg",
    address: {
      streetAddress: "67 Maple Ave",
      areaOrVillage: "Springfield",
      district: "Central District",
    },
    age: 31,
    gender: "Female",
    designation: "UX Designer",
    isEmailVerified: false,
    role: "user",
    status: "active",
  },
  {
    name: "Frank Ocean",
    email: "frank@example.com",
    phoneNumber: "9988776655",
    password: "frankOcean",
    profileImage: "/images/users/frank.jpg",
    address: {
      streetAddress: "88 Ocean Dr",
      areaOrVillage: "Waterside",
      district: "Harbor District",
    },
    age: 45,
    gender: "Male",
    designation: "Data Scientist",
    isEmailVerified: true,
    role: "user",
    status: "active",
  },
  {
    name: "Grace Kim",
    email: "grace@example.com",
    phoneNumber: "1231231234",
    password: "grace789",
    profileImage: "/images/users/grace.jpg",
    address: {
      streetAddress: "123 Oak Street",
      areaOrVillage: "Pineville",
      district: "Northwest",
    },
    age: 27,
    gender: "Female",
    designation: "Support Specialist",
    isEmailVerified: true,
    role: "user",
    status: "inactive",
  },
  {
    name: "Henry Ford",
    email: "henry@example.com",
    phoneNumber: "7778889999",
    password: "fordPower",
    profileImage: "/images/users/henry.jpg",
    address: {
      streetAddress: "444 Motorway",
      areaOrVillage: "GearTown",
      district: "Tech District",
    },
    age: 50,
    gender: "Male",
    designation: "Project Manager",
    isEmailVerified: false,
    role: "special-user",
    status: "active",
  },
  {
    name: "Isabel Ruiz",
    email: "isabel@example.com",
    phoneNumber: "6667778888",
    password: "ruiz123",
    profileImage: "/images/users/isabel.jpg",
    address: {
      streetAddress: "999 Palm Way",
      areaOrVillage: "Tropicville",
      district: "Island Region",
    },
    age: 30,
    gender: "Female",
    designation: "HR Officer",
    isEmailVerified: true,
    role: "user",
    status: "inactive",
  },
  {
    name: "Jason Lee",
    email: "jason@example.com",
    phoneNumber: "4445556666",
    password: "jason456",
    profileImage: "/images/users/jason.jpg",
    address: {
      streetAddress: "555 Wind Ave",
      areaOrVillage: "Skytown",
      district: "Mountain District",
    },
    age: 36,
    gender: "Male",
    designation: "Developer Advocate",
    isEmailVerified: false,
    role: "special-user",
    status: "active",
  },
  {
    name: "Karen Black",
    email: "karen@example.com",
    phoneNumber: "1112223333",
    password: "blackKaren",
    profileImage: "/images/users/karen.jpg",
    address: {
      streetAddress: "22 Elm St",
      areaOrVillage: "Greentown",
      district: "East Borough",
    },
    age: 41,
    gender: "Female",
    designation: "Operations Lead",
    isEmailVerified: true,
    role: "user",
    status: "active",
  },
];
